
pool:
  vmImage: 'windows-2019'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview5-011568

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: Npm@1
  displayName: 'Install Npm packages'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Run release script'
  inputs:
    command: 'custom'
    customCommand: 'run release'